- name: Deploy application on Kubernetes
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Create product rating deployment
      k8s:
        kubeconfig: "~/.kube/config"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: product-rating-deployment
            namespace: tawasalna
            labels:
              app: my-app-rating
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: my-app-rating
            template:
              metadata:
                labels:
                  app: my-app-rating
              spec:
                containers:
                  - name: product-rating-container
                    image: brahim98/product-rating:v1.0.2-dev
                    imagePullPolicy: Always
                    ports:
                      - containerPort: 5004
                nodeSelector:
                  kubernetes.io/hostname: worker1

    - name: Create mlops product rating service
      k8s:
        state: present
        kubeconfig: "~/.kube/config"
        verify_ssl: no
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: product-rating-service
            namespace: tawasalna
            labels:
              app: my-app-rating
          spec:
            selector:
              app: my-app-rating
            ports:
              - protocol: TCP
                port: 8095
                targetPort: 5004
                nodePort: 30348
            type: NodePort
